name: Cleanup Short Runs


on:
  workflow_dispatch:
  schedule:
    - cron: '12 3 * * *'


jobs:
  cleanup:
    runs-on: ubuntu-latest
    permissions:
      actions: write
      
    steps:
    - name: Delete short runs
      env:
        GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
        # Get workflow runs
        curl -s -H "Authorization: Bearer $GH_TOKEN" \
          "https://api.github.com/repos/${{ github.repository }}/actions/runs?status=completed&per_page=100" > runs.json
       
        if [ $? -ne 0 ]; then
          echo "Error: Failed to fetch workflow runs."
          exit 1
        fi

        # Filter and delete runs with duration < 120s
        jq -r '
          .workflow_runs[] | 
          select(
            ( (.updated_at | fromdateiso8601) - (.created_at | fromdateiso8601) ) < 120  # Duration check
            or 
            (now - (.updated_at | fromdateiso8601) ) > (90|.*24*60*60)  # 90-day expiration
          ) | .id
        ' runs.json | while read -r run_id; do
          echo "Deleting run $run_id"
          curl -s -X DELETE -H "Authorization: Bearer $GH_TOKEN" \
            "https://api.github.com/repos/${{ github.repository }}/actions/runs/$run_id"
        done
